#!/usr/bin/env python
import sys
from argparse import ArgumentParser, Namespace
from os.path import dirname
from unittest.mock import patch


def echo(cmd, **_):
    return ' '.join(cmd).encode()


if __name__ == '__main__':
    root: str = dirname(dirname(__file__))
    sys.path.append(root)

    from src.cli import get_parser

    parser: ArgumentParser = get_parser()
    args: Namespace = parser.parse_args()
    with patch('src.helpers.check_output', echo):
        stdout: str = args.func(**vars(args))
        print(stdout)
