#!/usr/bin/env python
import logging
import sys
from argparse import ArgumentParser, Namespace
from os.path import dirname

if __name__ == "__main__":
    root: str = dirname(dirname(__file__))
    sys.path.append(root)

    from src.cli import get_parser

    logging.basicConfig(level='DEBUG')
    parser: ArgumentParser = get_parser()
    args: Namespace = parser.parse_args()
    print(args.calendar)
    print(args.loglevel)
