#!/usr/bin/env python
import sys
from argparse import Namespace
from os.path import dirname

if __name__ == "__main__":
    root: str = dirname(dirname(__file__))
    sys.path.append(root)

    from src.cli import KhalOrgParser

    parser: KhalOrgParser = KhalOrgParser()
    args: Namespace = parser.parse_args()
    print(args.calendar)
    print(args.logging)
