#!/usr/bin/env python
import sys
from argparse import Namespace
from os.path import dirname
from unittest.mock import patch


def echo(cmd):
    return ' '.join(cmd).encode()


if __name__ == '__main__':
    root: str = dirname(dirname(__file__))
    sys.path.append(root)

    from src.cli import CLI, main

    parser = CLI()
    args: Namespace = parser.parse_args()
    with patch('src.helpers.check_output', echo):
        stdout: str = main(args.command, args.calendar)
        print(stdout)
