#!/usr/bin/env python
import sys
from argparse import Namespace
from os.path import dirname

if __name__ == "__main__":
    sys.path.append(dirname(dirname(__file__)))

    from src.helpers import OrgToKhalParser

    parser: OrgToKhalParser = OrgToKhalParser()
    args: Namespace = parser.parse_args()
    print(args.calendar)
    print(args.logging)
