#!/usr/bin/env python

""" Export an org agenda item to a khal calendar. """

from argparse import Namespace

from src.cli import KhalOrgParser, main

if __name__ == '__main__':
    parser = KhalOrgParser()
    args: Namespace = parser.parse_args()
    stdout: str = main(**vars(args))
    print(stdout)
