#!/usr/bin/env python

""" Export an org agenda item to a khal calendar. """

import logging
from argparse import Namespace

from src.cli import KhalOrgParser, main

if __name__ == '__main__':
    parser = KhalOrgParser()
    args: Namespace = parser.parse_args()
    logging.basicConfig(level=args.logging)
    stdout: str = main(args.command, args.calendar)
    print(stdout)
