#!/usr/bin/env python

""" Export an org agenda item to a khal calendar. """

from argparse import Namespace

from src.cli import get_parser, main

if __name__ == '__main__':
    parser = get_parser()
    args: Namespace = parser.parse_args()
    stdout: str = main(**vars(args))
    print(stdout)
