#!/usr/bin/env python
import logging
from argparse import Namespace

from src.org_to_khal import main, CommandLineInterface

if __name__ == '__main__':
    parser = CommandLineInterface()
    args: Namespace = parser.parse_args()
    logging.basicConfig(level=args.logging)
    stdout: str = main(args.calendar)
    print(stdout)
