#!/usr/bin/env python
from argparse import Namespace
import logging
from src.org_to_khal import org_to_khal
from src.helpers import CustomParser

if __name__ == '__main__':
    parser = CustomParser()
    args: Namespace = parser.parse_args()
    logging.basicConfig(level=args.logging)
    org_to_khal(args.calendar)
