#!/usr/bin/env python
import logging
from argparse import Namespace

from src.helpers import OrgToKhalParser
from src.org_to_khal import org_to_khal

if __name__ == '__main__':
    parser = OrgToKhalParser()
    args: Namespace = parser.parse_args()
    logging.basicConfig(level=args.logging)
    org_to_khal(args.calendar)
